# Generated by Django 6.0.3 on 2026-09-12 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('nacionalidad', models.CharField(max_length=80)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('fecha_publicacion', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('disponible', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='libros', to='biblioteca.autor')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinopsis', models.TextField()),
                ('numero_paginas', models.PositiveIntegerField()),
                ('idioma_original', models.CharField(max_length=50)),
                ('edicion', models.CharField(blank=True, max_length=50)),
                ('libro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_tecnica', to='biblioteca.libro')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(auto_now_add=True)),
                ('fecha_devolucion_esperada', models.DateField()),
                ('fecha_devolucion_real', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PRESTADO', 'Prestado'), ('DEVUELTO', 'Devuelto'), ('ATRASADO', 'Atrasado')], default='PRESTADO', max_length=10)),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='biblioteca.lector')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='biblioteca.libro')),
            ],
            options={
                'ordering': ['-fecha_prestamo'],
            },
        ),
        migrations.AddField(
            model_name='libro',
            name='lectores',
            field=models.ManyToManyField(blank=True, related_name='libros_leidos', through='biblioteca.Prestamo', to='biblioteca.lector'),
        ),
    ]
